from .gradient_descend import gradient_descend
from .conj_gradient_descend import conj_gradient_descend
from .newton_raphson import newton_raphson
from .internal_penalty import internal_penalty
from .external_penalty import external_penalty